### ISSUE TITLE
Implement custom app button component

### ISSUE THREAD

**Issue by mark-trann** [devsoc-unsw/trainee-uranus-24t1#13]
### Description

We need our custom button (see below) for the user onboarding experience.

![image](https://github.com/devsoc-unsw/trainee-uranus-24t1/assets/29350857/0a168061-05dd-4272-9d9a-eb86560a7a43)

### Requirements

- component should be able to display text based on input

### Acceptance Criteria

- changes can be locally recreated and component fits design prototype

**Comment by chinosu** [comment]
<img width="129" alt="image" src="https://github.com/devsoc-unsw/trainee-uranus-24t1/assets/46995931/c8a2277d-90f9-44a8-851d-7b708bb3b5ce">
